[build]
  publish = "_site"
  command = "npm run build"
[[redirects]]

  [redirects.404]
    from = "/*"
    to = "/404/"
    status = 404

  [redirects.services]
    from = "/services"
    to = "/leistungen"
    status = 302

  [redirects.references]
    from = "/references"
    to = "/referenzen"
    status = 302

  [redirects.about]
    from = "/about"
    to = "/ueber-uns"
    status = 302
