[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/services"
  to = "/leistungen"
  status = 301

[[redirects]]
  from = "/references"
  to = "/referenzen"
  status = 301

[[redirects]]
  from = "/about"
  to = "/ueber-uns"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
